### ISSUE TITLE
Can you realize esx_carthiefjob if you can

### ISSUE THREAD

**Issue by eskapel** [TheGreyRaven/FiveM-Resource-Project#1]
Can you realize esx_carthiefjob if you can

**Comment by TheGreyRaven** [comment]
The scripts here are *automatically* fetched and uploaded, if the bot finds a carthiefjob it will then upload it. Its nothing that I will do manually, though the bot has been offline now for a couple of days due to improvements.

I will re-run the bot today and maybe it will find the script you are looking for.
